# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Hence
# Description of the Site
description: The Personal Website of Hence
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: ../images/background.png
# https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: zhiwenhu72@gmail.com
facebook_username:  # Nikola Hu   #中国大陆地区好像不给用直接的链接
twitter_username: 
instagram_username: 
linkedin_username: 
github_username: HenceHzw
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

qq_qrcode: assets/images/qrcode_1739517322107.jpg

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Hence
# URL for the Image of the Author
author-image: assets/images/author_image.jpg
# 60 Words About the Author
author-about: A XJTUer | If you find some mistakes in my blog, please contact me to correct them. Thank you!
author-url: https://github.com/HenceHzw

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-katex


markdown: kramdown
highlighter: rouge

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
